package com.hehaoyisheng.bcgame.common;

import com.google.common.collect.Lists;
import com.google.common.collect.Maps;
import com.hehaoyisheng.bcgame.entity.vo.Bank;
import com.hehaoyisheng.bcgame.entity.vo.Province;

import java.util.List;
import java.util.Map;

public class BaseData {
    public final static List<Bank> bankName = Lists.newArrayList();
    public final static List<Province> province = Lists.newArrayList();
    public final static Map<Integer, List<String>> cityList = Maps.newHashMap();

    static {
        bankName.add(new Bank(1, "中国工商银行"));
        bankName.add(new Bank(2, "中国银行"));
        bankName.add(new Bank(3, "中国农业银行"));
        bankName.add(new Bank(4, "中国建设银行"));
        bankName.add(new Bank(11, "中国光大银行"));
        bankName.add(new Bank(12, "兴业银行"));
        bankName.add(new Bank(14, "招商银行"));
        bankName.add(new Bank(15, "中国民生银行"));
        bankName.add(new Bank(16, "交通银行"));
        bankName.add(new Bank(25, "中国邮政储蓄银行"));
        bankName.add(new Bank(28, "平安银行"));
        bankName.add(new Bank(29, "浦发银行"));
        bankName.add(new Bank(33, "微信扫码"));
        bankName.add(new Bank(38, "支付宝扫码"));

        province.add(new Province(10, "北京"));
        province.add(new Province(11, "上海"));
        province.add(new Province(12, "天津"));
        province.add(new Province(13, "重庆"));
        province.add(new Province(14, "河北"));
        province.add(new Province(15, "山西"));
        province.add(new Province(16, "内蒙古"));
        province.add(new Province(17, "辽宁"));
        province.add(new Province(18, "吉林"));
        province.add(new Province(19, "黑龙江"));
        province.add(new Province(20, "江苏"));
        province.add(new Province(21, "浙江"));
        province.add(new Province(22, "安徽"));
        province.add(new Province(23, "福建"));
        province.add(new Province(24, "江西"));
        province.add(new Province(25, "山东"));
        province.add(new Province(26, "河南"));
        province.add(new Province(27, "湖北"));
        province.add(new Province(28, "湖南"));
        province.add(new Province(29, "广东"));
        province.add(new Province(30, "广西"));
        province.add(new Province(31, "海南"));
        province.add(new Province(32, "四川"));
        province.add(new Province(33, "贵州"));
        province.add(new Province(34, "云南"));
        province.add(new Province(35, "西藏"));
        province.add(new Province(36, "陕西"));
        province.add(new Province(37, "甘肃"));
        province.add(new Province(38, "青海"));
        province.add(new Province(39, "宁夏"));
        province.add(new Province(40, "新疆"));
        province.add(new Province(41, "香港"));
        province.add(new Province(42, "澳门"));
        province.add(new Province(43, "台湾"));

        List<String> cityList10 = Lists.newArrayList();
        cityList10.add("东城区");
        cityList10.add("西城区");
        cityList10.add("崇文区");
        cityList10.add("宣武区");
        cityList10.add("朝阳区");
        cityList10.add("丰台区");
        cityList10.add("石景山区");
        cityList10.add("海淀区");
        cityList10.add("门头沟区");
        cityList10.add("房山区");
        cityList10.add("通州区");
        cityList10.add("顺义区");
        cityList10.add("昌平区");
        cityList10.add("大兴区");
        cityList10.add("怀柔区");
        cityList10.add("平谷区");
        cityList10.add("密云县");
        cityList10.add("延庆县");
        cityList.put(10, cityList10);
        List<String> cityList11 = Lists.newArrayList();
        cityList11.add("黄浦区");
        cityList11.add("卢湾区");
        cityList11.add("徐汇区");
        cityList11.add("长宁区");
        cityList11.add("静安区");
        cityList11.add("普陀区");
        cityList11.add("闸北区");
        cityList11.add("虹口区");
        cityList11.add("杨浦区");
        cityList11.add("闵行区");
        cityList11.add("宝山区");
        cityList11.add("嘉定区");
        cityList11.add("浦东新区");
        cityList11.add("金山区");
        cityList11.add("松江区");
        cityList11.add("青浦区");
        cityList11.add("南汇区");
        cityList11.add("奉贤区");
        cityList11.add("崇明县");
        cityList.put(11, cityList11);
        List<String> cityList12 = Lists.newArrayList();
        cityList12.add("和平区");
        cityList12.add("河东区");
        cityList12.add("河西区");
        cityList12.add("南开区");
        cityList12.add("河北区");
        cityList12.add("红桥区");
        cityList12.add("塘沽区");
        cityList12.add("汉沽区");
        cityList12.add("大港区");
        cityList12.add("东丽区");
        cityList12.add("西青区");
        cityList12.add("津南区");
        cityList12.add("北辰区");
        cityList12.add("武清区");
        cityList12.add("宝坻区");
        cityList12.add("宁河县");
        cityList12.add("静海县");
        cityList12.add("蓟县");
        cityList.put(12, cityList12);
        List<String> cityList13 = Lists.newArrayList();
        cityList13.add("万州区");
        cityList13.add("涪陵区");
        cityList13.add("渝中区");
        cityList13.add("大渡口区");
        cityList13.add("江北区");
        cityList13.add("沙坪坝区");
        cityList13.add("九龙坡区");
        cityList13.add("南岸区");
        cityList13.add("北碚区");
        cityList13.add("万盛区");
        cityList13.add("双桥区");
        cityList13.add("渝北区");
        cityList13.add("巴南区");
        cityList13.add("黔江区");
        cityList13.add("长寿区");
        cityList13.add("綦江县");
        cityList13.add("潼南县");
        cityList13.add("铜梁县");
        cityList13.add("大足县");
        cityList13.add("荣昌县");
        cityList13.add("璧山县");
        cityList13.add("梁平县");
        cityList13.add("城口县");
        cityList13.add("丰都县");
        cityList13.add("垫江县");
        cityList13.add("武隆县");
        cityList13.add("忠县");
        cityList13.add("开县");
        cityList13.add("云阳县");
        cityList13.add("奉节县");
        cityList13.add("巫山县");
        cityList13.add("巫溪县");
        cityList13.add("石柱土家族自治县");
        cityList13.add("秀山土家族苗族自治县");
        cityList13.add("酉阳土家族苗族自治县");
        cityList13.add("彭水苗族土家族自治县");
        cityList13.add("江津市");
        cityList13.add("合川市");
        cityList13.add("永川市");
        cityList13.add("南川市");
        cityList.put(13, cityList13);
        List<String> cityList14 = Lists.newArrayList();
        cityList14.add("石家庄");
        cityList14.add("唐山");
        cityList14.add("秦皇岛");
        cityList14.add("邯郸");
        cityList14.add("邢台");
        cityList14.add("保定");
        cityList14.add("张家口");
        cityList14.add("承德");
        cityList14.add("沧州");
        cityList14.add("廊坊");
        cityList14.add("衡水");
        cityList.put(14, cityList14);
        List<String> cityList15 = Lists.newArrayList();
        cityList15.add("太原");
        cityList15.add("大同");
        cityList15.add("阳泉");
        cityList15.add("长治");
        cityList15.add("晋城");
        cityList15.add("朔州");
        cityList15.add("晋中");
        cityList15.add("运城");
        cityList15.add("忻州");
        cityList15.add("临汾");
        cityList15.add("吕梁");
        cityList.put(15, cityList15);
        List<String> cityList16 = Lists.newArrayList();
        cityList16.add("呼和浩特");
        cityList16.add("包头");
        cityList16.add("乌海");
        cityList16.add("赤峰");
        cityList16.add("通辽");
        cityList16.add("鄂尔多斯");
        cityList16.add("呼伦贝尔");
        cityList16.add("乌兰察布");
        cityList16.add("锡林郭勒盟");
        cityList16.add("巴彦淖尔");
        cityList16.add("阿拉善盟");
        cityList16.add("兴安盟");
        cityList.put(16, cityList16);
        List<String> cityList17 = Lists.newArrayList();
        cityList17.add("沈阳");
        cityList17.add("大连");
        cityList17.add("鞍山");
        cityList17.add("抚顺");
        cityList17.add("本溪");
        cityList17.add("丹东");
        cityList17.add("锦州");
        cityList17.add("葫芦岛");
        cityList17.add("营口");
        cityList17.add("盘锦");
        cityList17.add("阜新");
        cityList17.add("辽阳");
        cityList17.add("铁岭");
        cityList17.add("朝阳");
        cityList.put(17, cityList17);
        List<String> cityList18 = Lists.newArrayList();
        cityList18.add("长春");
        cityList18.add("吉林");
        cityList18.add("四平");
        cityList18.add("辽源");
        cityList18.add("通化");
        cityList18.add("白山");
        cityList18.add("松原");
        cityList18.add("白城");
        cityList18.add("延边朝鲜");
        cityList.put(18, cityList18);
        List<String> cityList19 = Lists.newArrayList();
        cityList19.add("哈尔滨");
        cityList19.add("齐齐哈尔");
        cityList19.add("鹤岗");
        cityList19.add("双鸭山");
        cityList19.add("鸡西");
        cityList19.add("大庆");
        cityList19.add("伊春");
        cityList19.add("牡丹江");
        cityList19.add("佳木斯");
        cityList19.add("七台河");
        cityList19.add("黑河");
        cityList19.add("绥化");
        cityList19.add("大兴安岭");
        cityList.put(19, cityList19);
        List<String> cityList20 = Lists.newArrayList();
        cityList20.add("南京");
        cityList20.add("无锡");
        cityList20.add("徐州");
        cityList20.add("常州");
        cityList20.add("苏州");
        cityList20.add("南通");
        cityList20.add("连云港");
        cityList20.add("淮安");
        cityList20.add("盐城");
        cityList20.add("扬州");
        cityList20.add("镇江");
        cityList20.add("泰州");
        cityList20.add("宿迁");
        cityList.put(20, cityList20);
        List<String> cityList21 = Lists.newArrayList();
        cityList21.add("杭州");
        cityList21.add("宁波");
        cityList21.add("温州");
        cityList21.add("嘉兴");
        cityList21.add("湖州");
        cityList21.add("绍兴");
        cityList21.add("金华");
        cityList21.add("衢州");
        cityList21.add("舟山");
        cityList21.add("台州");
        cityList21.add("丽水");
        cityList.put(21, cityList21);
        List<String> cityList22 = Lists.newArrayList();
        cityList22.add("合肥");
        cityList22.add("芜湖");
        cityList22.add("蚌埠");
        cityList22.add("淮南");
        cityList22.add("马鞍山");
        cityList22.add("淮北");
        cityList22.add("铜陵");
        cityList22.add("安庆");
        cityList22.add("黄山");
        cityList22.add("滁州");
        cityList22.add("阜阳");
        cityList22.add("宿州");
        cityList22.add("巢湖");
        cityList22.add("六安");
        cityList22.add("亳州");
        cityList22.add("池州");
        cityList22.add("宣城");
        cityList.put(22, cityList22);
        List<String> cityList23 = Lists.newArrayList();
        cityList23.add("福州");
        cityList23.add("厦门");
        cityList23.add("莆田");
        cityList23.add("三明");
        cityList23.add("泉州");
        cityList23.add("漳州");
        cityList23.add("南平");
        cityList23.add("龙岩");
        cityList23.add("宁德");
        cityList.put(23, cityList23);
        List<String> cityList24 = Lists.newArrayList();
        cityList24.add("南昌");
        cityList24.add("景德镇");
        cityList24.add("萍乡");
        cityList24.add("新余");
        cityList24.add("九江");
        cityList24.add("鹰潭");
        cityList24.add("赣州");
        cityList24.add("吉安");
        cityList24.add("宜春");
        cityList24.add("抚州");
        cityList24.add("上饶");
        cityList.put(24, cityList24);
        List<String> cityList25 = Lists.newArrayList();
        cityList25.add("济南");
        cityList25.add("青岛");
        cityList25.add("淄博");
        cityList25.add("枣庄");
        cityList25.add("东营");
        cityList25.add("潍坊");
        cityList25.add("烟台");
        cityList25.add("威海");
        cityList25.add("济宁");
        cityList25.add("泰安");
        cityList25.add("日照");
        cityList25.add("莱芜");
        cityList25.add("德州");
        cityList25.add("临沂");
        cityList25.add("聊城");
        cityList25.add("滨州");
        cityList25.add("菏泽");
        cityList.put(25, cityList25);
        List<String> cityList26 = Lists.newArrayList();
        cityList26.add("郑州");
        cityList26.add("开封");
        cityList26.add("洛阳");
        cityList26.add("平顶山");
        cityList26.add("焦作");
        cityList26.add("鹤壁");
        cityList26.add("新乡");
        cityList26.add("安阳");
        cityList26.add("濮阳");
        cityList26.add("许昌");
        cityList26.add("漯河");
        cityList26.add("三门峡");
        cityList26.add("南阳");
        cityList26.add("商丘");
        cityList26.add("信阳");
        cityList26.add("周口");
        cityList26.add("驻马店");
        cityList26.add("济源");
        cityList.put(26, cityList26);
        List<String> cityList27 = Lists.newArrayList();
        cityList27.add("武汉");
        cityList27.add("黄石");
        cityList27.add("襄樊");
        cityList27.add("十堰");
        cityList27.add("荆州");
        cityList27.add("宜昌");
        cityList27.add("荆门");
        cityList27.add("鄂州");
        cityList27.add("孝感");
        cityList27.add("黄冈");
        cityList27.add("咸宁");
        cityList27.add("随州");
        cityList27.add("仙桃");
        cityList27.add("天门");
        cityList27.add("潜江");
        cityList27.add("神农架");
        cityList27.add("恩施土家");
        cityList.put(27, cityList27);
        List<String> cityList28 = Lists.newArrayList();
        cityList28.add("长沙");
        cityList28.add("株洲");
        cityList28.add("湘潭");
        cityList28.add("衡阳");
        cityList28.add("邵阳");
        cityList28.add("岳阳");
        cityList28.add("常德");
        cityList28.add("张家界");
        cityList28.add("益阳");
        cityList28.add("郴州");
        cityList28.add("怀化");
        cityList28.add("娄底");
        cityList28.add("湘西土家");
        cityList28.add("永州");
        cityList.put(28, cityList28);
        List<String> cityList29 = Lists.newArrayList();
        cityList29.add("广州");
        cityList29.add("深圳");
        cityList29.add("珠海");
        cityList29.add("汕头");
        cityList29.add("韶关");
        cityList29.add("佛山");
        cityList29.add("江门");
        cityList29.add("湛江");
        cityList29.add("茂名");
        cityList29.add("肇庆");
        cityList29.add("惠州");
        cityList29.add("梅州");
        cityList29.add("汕尾");
        cityList29.add("河源");
        cityList29.add("阳江");
        cityList29.add("清远");
        cityList29.add("东莞");
        cityList29.add("中山");
        cityList29.add("潮州");
        cityList29.add("揭阳");
        cityList29.add("云浮");
        cityList.put(29, cityList29);
        List<String> cityList30 = Lists.newArrayList();
        cityList30.add("南宁");
        cityList30.add("柳州");
        cityList30.add("桂林");
        cityList30.add("梧州");
        cityList30.add("北海");
        cityList30.add("防城港");
        cityList30.add("钦州");
        cityList30.add("贵港");
        cityList30.add("玉林");
        cityList30.add("百色");
        cityList30.add("贺州");
        cityList30.add("河池");
        cityList30.add("来宾");
        cityList30.add("崇左");
        cityList.put(30, cityList30);
        List<String> cityList31 = Lists.newArrayList();
        cityList31.add("海口");
        cityList31.add("三亚");
        cityList31.add("五指山");
        cityList31.add("琼海");
        cityList31.add("儋州");
        cityList31.add("文昌");
        cityList31.add("万宁");
        cityList31.add("东方");
        cityList31.add("澄迈");
        cityList31.add("定安");
        cityList31.add("屯昌");
        cityList31.add("临高");
        cityList31.add("白沙黎族");
        cityList31.add("江黎族自");
        cityList31.add("乐东黎族");
        cityList31.add("陵水黎族");
        cityList31.add("保亭黎族");
        cityList31.add("琼中黎族");
        cityList31.add("西沙群岛");
        cityList31.add("南沙群岛");
        cityList31.add("中沙群岛");
        cityList.put(31, cityList31);
        List<String> cityList32 = Lists.newArrayList();
        cityList32.add("成都");
        cityList32.add("自贡");
        cityList32.add("攀枝花");
        cityList32.add("泸州");
        cityList32.add("德阳");
        cityList32.add("绵阳");
        cityList32.add("广元");
        cityList32.add("遂宁");
        cityList32.add("内江");
        cityList32.add("乐山");
        cityList32.add("南充");
        cityList32.add("宜宾");
        cityList32.add("广安");
        cityList32.add("达州");
        cityList32.add("眉山");
        cityList32.add("雅安");
        cityList32.add("巴中");
        cityList32.add("资阳");
        cityList32.add("阿坝藏族");
        cityList32.add("甘孜藏族");
        cityList32.add("凉山彝族");
        cityList.put(32, cityList32);
        List<String> cityList33 = Lists.newArrayList();
        cityList33.add("贵阳");
        cityList33.add("六盘水");
        cityList33.add("遵义");
        cityList33.add("安顺");
        cityList33.add("铜仁");
        cityList33.add("毕节");
        cityList33.add("黔西南布");
        cityList33.add("黔东南苗");
        cityList33.add("黔南布依");
        cityList.put(33, cityList33);
        List<String> cityList34 = Lists.newArrayList();
        cityList34.add("昆明");
        cityList34.add("曲靖");
        cityList34.add("玉溪");
        cityList34.add("保山");
        cityList34.add("昭通");
        cityList34.add("丽江");
        cityList34.add("思茅");
        cityList34.add("临沧");
        cityList34.add("文山壮族");
        cityList34.add("红河哈尼");
        cityList34.add("西双版纳");
        cityList34.add("楚雄彝族");
        cityList34.add("大理白族");
        cityList34.add("德宏傣族");
        cityList34.add("怒江傈傈");
        cityList34.add("迪庆藏族");
        cityList.put(34, cityList34);
        List<String> cityList35 = Lists.newArrayList();
        cityList35.add("拉萨");
        cityList35.add("那曲");
        cityList35.add("昌都");
        cityList35.add("山南");
        cityList35.add("日喀则");
        cityList35.add("阿里");
        cityList35.add("林芝");
        cityList.put(35, cityList35);
        List<String> cityList36 = Lists.newArrayList();
        cityList36.add("西安");
        cityList36.add("铜川");
        cityList36.add("宝鸡");
        cityList36.add("咸阳");
        cityList36.add("渭南");
        cityList36.add("延安");
        cityList36.add("汉中");
        cityList36.add("榆林");
        cityList36.add("安康");
        cityList36.add("商洛");
        cityList.put(36, cityList36);
        List<String> cityList37 = Lists.newArrayList();
        cityList37.add("兰州");
        cityList37.add("金昌");
        cityList37.add("白银");
        cityList37.add("天水");
        cityList37.add("嘉峪关");
        cityList37.add("武威");
        cityList37.add("张掖");
        cityList37.add("平凉");
        cityList37.add("酒泉");
        cityList37.add("庆阳");
        cityList37.add("定西");
        cityList37.add("陇南");
        cityList37.add("临夏回族");
        cityList37.add("甘南藏族");
        cityList.put(37, cityList37);
        List<String> cityList38 = Lists.newArrayList();
        cityList38.add("西宁");
        cityList38.add("海东");
        cityList38.add("海北藏族");
        cityList38.add("黄南藏族");
        cityList38.add("海南藏族");
        cityList38.add("果洛藏族");
        cityList38.add("玉树藏族");
        cityList38.add("海西蒙古");
        cityList.put(38, cityList38);
        List<String> cityList39 = Lists.newArrayList();
        cityList39.add("银川");
        cityList39.add("石嘴山");
        cityList39.add("吴忠");
        cityList39.add("固原");
        cityList39.add("中卫");
        cityList.put(39, cityList39);
        List<String> cityList40 = Lists.newArrayList();
        cityList40.add("乌鲁木齐");
        cityList40.add("克拉玛依");
        cityList40.add("石河子");
        cityList40.add("阿拉尔");
        cityList40.add("图木舒克");
        cityList40.add("五家渠");
        cityList40.add("吐鲁番");
        cityList40.add("哈密");
        cityList40.add("和田");
        cityList40.add("阿克苏");
        cityList40.add("喀什");
        cityList40.add("克孜勒苏");
        cityList40.add("巴音郭楞");
        cityList40.add("昌吉回族");
        cityList40.add("博尔塔拉");
        cityList40.add("伊犁哈萨");
        cityList40.add("塔城");
        cityList40.add("阿勒泰");
        cityList.put(40, cityList40);
        List<String> cityList41 = Lists.newArrayList();
        cityList.put(41, cityList41);
        List<String> cityList42 = Lists.newArrayList();
        cityList.put(42, cityList42);
        List<String> cityList43 = Lists.newArrayList();
        cityList43.add("台北");
        cityList43.add("高雄");
        cityList43.add("基隆");
        cityList43.add("台中");
        cityList43.add("台南");
        cityList43.add("新竹");
        cityList43.add("嘉义");
        cityList43.add("台北县");
        cityList43.add("宜兰县");
        cityList43.add("新竹县");
        cityList43.add("桃园县");
        cityList43.add("苗栗县");
        cityList43.add("台中县");
        cityList43.add("彰化县");
        cityList43.add("南投县");
        cityList43.add("嘉义县");
        cityList43.add("云林县");
        cityList43.add("台南县");
        cityList43.add("高雄县");
        cityList43.add("屏东县");
        cityList43.add("台东县");
        cityList43.add("花莲县");
        cityList43.add("澎湖县");
        cityList.put(43, cityList43);
    }
}
